version: "3"
services:
    jpnb:
        image: python_flask_example
        build: 
            context: ./
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
        volumes:
            - ./:/app
