version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch 

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build container
          command: docker build -t tmp .



