version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch 

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build container
          command: docker build -t tmp .

      - run:
          name: BB test
          command: |
                docker run -d -p 3000:3000 tmp
                sleep 5
                docker ps
                curl http://127.0.0.1:3000/
                ./tests/blackbox_tests/test.sh
                

